config/routes.rb
Rails.application.routes.draw do
  resources :links do
    resources :comments
    patch 'add_one'
    patch 'subtract_one'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :link

  validates :content, :author, :presence => true
end

app/models/link.rb
class Link < ActiveRecord::Base

  has_many :comments

  validates :title, :url, :score, :presence => true

  after_initialize :init

  def init
    self.score ||= 0.0
  end

  def age
    self.score -= 1
  end

  def add_one
    self.score += 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new
  end

  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    if @comment.save
      redirect_to link_path(@comment.link)
    else
      render :new
    end
  end

  

  private
    def comment_params
      params.require(:comment).permit(:author, :content)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.order('score DESC')
  end

  def show
    @link = Link.find(params[:id])
    render :show
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to links_path
    else
      render :new
    end
  end

    def edit
      @link = Link.find(params[:id])
    end

    def update
      @link = Link.find(params[:id])
    end

  def add_one
    @link = Link.find(params[:link_id])
    @link.score += 1
    @link.save
    redirect_to(links_path)
  end

  def subtract_one
    @link = Link.find(params[:link_id])
    @link.score -= 1
    @link.save
    redirect_to(links_path)
  end

  private
  def link_params
    params.require(:link).permit(:title, :url, :score)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= render('layouts/errors', :object => @comment) %>

<%= form_for [@link, @comment] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <p><%= f.submit %></p>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment for <%= @link.title %></h1>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackerNews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-title">
        <h1>Bad Millenial News</h1>

      </div>
    </header>
    <section>
      <%= yield %>
    </section>
  </body>
</html>

app/views/links/_form.html.erb
<%= render "layouts/errors", :object => @link %>

<%= form_for @link do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :url %>
  <%= f.text_field :url%>
  <%= f.submit %>
<% end %>

<p> <%= link_to "Return to links", links_path  %></p>

app/views/links/edit.html.erb
<h1>Edit Link</h1>

<%= render "form" %>

app/views/links/index.html.erb
<h1>Links</h1>
<ul>
  <% @links.each do |link| %>
    <li><%= link_to link.title, link.url%></li>
    <h5>Score: <%= link.score %>
      <%= link_to  "Comments", link_path(link), :class => "btn btn-default"%>
      <%= link_to  "Upvote", link_add_one_path(link), method: :patch, :class => "btn btn-default"%>
      <%= link_to  "Downvote", link_subtract_one_path(link), method: :patch, :class => "btn btn-default"%>
    </h5>
  <% end %>
</ul>

<%= link_to "Add New Link", new_link_path, :class => "btn btn-default" %>

app/views/links/new.html.erb
<h1>New Link!</h1>

<%= render "form" %>

app/views/links/show.html.erb
<h1><%= @link.title %></h1>

<% if @link.comments.any? %>
  <h4>Comments: </h4>
  <ul>
    <% @link.comments.each do |comment| %>
      <li>
        <h5><%= comment.author %></h5>
        <p><%= comment.content %></p>
      </li>
    <% end %>
  </ul>
<% else %>
<p>There are no comments. Please contribute to this discussion :)</p>
<% end %>

<p><%= link_to "New Comment", new_link_comment_path(@link) %></p>
<p><%= link_to "Return to Links", links_path %></p>